apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: cloudrun-canary-pipeline
description: Cloud Run pipeline with canary rollout
serialPipeline:
  stages:
    - targetId: dev
      strategy:
        standard:
          verify: false
    - targetId: qa
      strategy:
        standard:
          verify: false
    - targetId: prod
      strategy:
        canary:
          runtimeConfig:
            cloudRun:
              automaticTrafficControl: true
          canaryDeployment:
            percentages: [50, 100]
          verify: false
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
description: Dev environment
run:
  location: projects/mythic-beanbag-463309-e9/locations/asia-south1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: qa
description: QA environment
run:
  location: projects/mythic-beanbag-463309-e9/locations/asia-south1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
description: Prod environment
run:
  location: projects/mythic-beanbag-463309-e9/locations/asia-south1
