steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t', 'asia-south1-docker.pkg.dev/mythic-beanbag-463309-e9/my-repo/app:${_BUILD_ID}',
        '.'
      ]

  # Step 2: Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'asia-south1-docker.pkg.dev/mythic-beanbag-463309-e9/my-repo/app:${_BUILD_ID}'
      ]

  # Step 3: Apply Cloud Deploy pipeline and targets
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'gcloud'
    args:
      [
        'deploy', 'apply',
        '--file=clouddeploy.yaml',
        '--region=${_REGION}',
        '--project=mythic-beanbag-463309-e9'
      ]

  # Step 4: Wait for propagation
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - -c
      - |
        echo "Waiting for Cloud Deploy resources to become available..."
        sleep 60

  # Step 5: Create release and trigger deployment
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'gcloud'
    args:
      [
        'deploy', 'releases', 'create', '${_BUILD_ID}',
        '--delivery-pipeline', 'cloudrun-canary-pipeline',
        '--region', '${_REGION}',
        '--images', 'app=asia-south1-docker.pkg.dev/mythic-beanbag-463309-e9/my-repo/app:${_BUILD_ID}',
        '--project=mythic-beanbag-463309-e9'
      ]

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: asia-south1
  _BUILD_ID: rel-20240624-001

# Make sure this service account has Cloud Deploy + Artifact Registry + Cloud Run permissions
serviceAccount: 956387703564-compute@developer.gserviceaccount.com
