steps:
  # Step 0: Generate dynamic BUILD_ID (UTC timestamped)
  - name: 'gcr.io/cloud-builders/gcloud'
    id: generate-build-id
    entrypoint: 'bash'
    args:
      - -c
      - |
        BUILD_ID="rel-$(date -u +%Y%m%d-%H%M%S)"
        echo "BUILD_ID=$BUILD_ID" > build.env

  # Step 1: Build Docker image using BUILD_ID
  - name: 'gcr.io/cloud-builders/docker'
    id: docker-build
    entrypoint: 'bash'
    args:
      - -c
      - |
        source build.env
        docker build -t asia-south1-docker.pkg.dev/mythic-beanbag-463309-e9/my-repo/app:$$BUILD_ID .

  # Step 2: Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: docker-push
    entrypoint: 'bash'
    args:
      - -c
      - |
        source build.env
        docker push asia-south1-docker.pkg.dev/mythic-beanbag-463309-e9/my-repo/app:$$BUILD_ID

  # Step 3: Apply Cloud Deploy resources
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: deploy-apply
    args:
      [
        "deploy", "apply",
        "--file=clouddeploy.yaml",
        "--region=asia-south1",
        "--project=mythic-beanbag-463309-e9"
      ]

  # Step 4: Wait for resources to propagate
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: wait
    entrypoint: 'bash'
    args: ['-c', 'echo "Waiting for Cloud Deploy resources to propagate..."; sleep 60']

  # Step 5: Create Cloud Deploy release using BUILD_ID
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: create-release
    entrypoint: 'bash'
    args:
      - -c
      - |
        source build.env
        gcloud deploy releases create $$BUILD_ID \
          --delivery-pipeline=cloudrun-canary-pipeline \
          --region=asia-south1 \
          --images=app=asia-south1-docker.pkg.dev/mythic-beanbag-463309-e9/my-repo/app:$$BUILD_ID \
          --annotations=clouddeploy.googleapis.com/release-type=image \
          --project=mythic-beanbag-463309-e9

options:
  logging: CLOUD_LOGGING_ONLY

serviceAccount: 956387703564-compute@developer.gserviceaccount.com
