apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: cloudrun-canary-pipeline
description: Canary deployment pipeline for Cloud Run
serialPipeline:
  stages:
    - targetId: dev
      profiles: [dev]
    - targetId: qa
      profiles: [qa]
    - targetId: prod
      profiles: [prod]
      strategy:
        canary:
          percentages: [25, 50, 100]
          runtimeConfig:
            cloudRun:
              automaticTrafficControl: true
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
description: Cloud Run dev environment
run:
  location: projects/mythic-beanbag-463309-e9/locations/asia-south1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: qa
description: Cloud Run QA environment
run:
  location: projects/mythic-beanbag-463309-e9/locations/asia-south1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
description: Cloud Run prod environment
run:
  location: projects/mythic-beanbag-463309-e9/locations/asia-south1
