steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t', 'asia-south1-docker.pkg.dev/mythic-beanbag-463309-e9/my-repo/app:${_BUILD_ID}',
        '.'
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'asia-south1-docker.pkg.dev/mythic-beanbag-463309-e9/my-repo/app:${_BUILD_ID}'
      ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'gcloud'
    args:
      [
        "deploy", "apply",
        "--file=clouddeploy.yaml",
        "--region=${_REGION}",
        "--project=mythic-beanbag-463309-e9"
      ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - -c
      - |
        echo "Waiting for Cloud Deploy resources to become available..."
        sleep 60

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'gcloud'
    args:
      [
        'deploy', 'releases', 'create', '${_BUILD_ID}',
        '--delivery-pipeline', 'cloudrun-python-pipeline',
        '--region', '${_REGION}',
        '--images', 'app=asia-south1-docker.pkg.dev/mythic-beanbag-463309-e9/my-repo/app:${_BUILD_ID}',
        '--project=mythic-beanbag-463309-e9'
      ]

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: asia-south1
  _BUILD_ID: rel-20240624-001

serviceAccount: 956387703564-compute@developer.gserviceaccount.com
