apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: my-cloudrun-app
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: app
          ports:
            - containerPort: 8080
